"""renew

Revision ID: 0ddb1aea5067
Revises: 2479dac1d3ca
Create Date: 2022-09-07 15:20:12.666702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ddb1aea5067'
down_revision = '2479dac1d3ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_contacts', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('users_contacts', 'name_')
    op.add_column('users_info', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('users_info', 'name_')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_info', sa.Column('name_', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users_info', 'name')
    op.add_column('users_contacts', sa.Column('name_', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users_contacts', 'name')
    # ### end Alembic commands ###
