"""new_tables

Revision ID: 09df2bc15bd6
Revises: a1d046ce3bce
Create Date: 2022-09-07 12:41:29.809432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09df2bc15bd6'
down_revision = 'a1d046ce3bce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_contacts', 'address')
    op.drop_column('users_contacts', 'birthday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_contacts', sa.Column('birthday', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users_contacts', sa.Column('address', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
