"""renew_

Revision ID: 2479dac1d3ca
Revises: 6b3b05731279
Create Date: 2022-09-07 15:17:27.359347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2479dac1d3ca'
down_revision = '6b3b05731279'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_contacts', sa.Column('name_', sa.String(length=50), nullable=False))
    op.drop_column('users_contacts', 'name')
    op.add_column('users_info', sa.Column('name_', sa.String(length=50), nullable=False))
    op.drop_column('users_info', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_info', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users_info', 'name_')
    op.add_column('users_contacts', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users_contacts', 'name_')
    # ### end Alembic commands ###
