"""tables

Revision ID: a1d046ce3bce
Revises: 
Create Date: 2022-09-07 12:33:41.328720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d046ce3bce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts_to_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contacts_id', sa.Integer(), nullable=True),
    sa.Column('info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contacts_id'], ['users_contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['info_id'], ['users_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts_to_info')
    op.drop_table('users_info')
    op.drop_table('users_contacts')
    # ### end Alembic commands ###
