"""Init

Revision ID: 85c706f54771
Revises: 
Create Date: 2022-09-04 12:11:42.830339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c706f54771'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('names_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('second_name', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phones_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('names_contacts_m2m_emails_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_contact', sa.Integer(), nullable=True),
    sa.Column('email_contact', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email_contact'], ['emails_contacts.id'], ),
    sa.ForeignKeyConstraint(['name_contact'], ['names_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('names_contacts_m2m_phones_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_contact', sa.Integer(), nullable=True),
    sa.Column('phone_contact', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['name_contact'], ['names_contacts.id'], ),
    sa.ForeignKeyConstraint(['phone_contact'], ['phones_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.Column('names_contacts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['names_contacts_id'], ['names_contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    op.drop_table('names_contacts_m2m_phones_contacts')
    op.drop_table('names_contacts_m2m_emails_contacts')
    op.drop_table('phones_contacts')
    op.drop_table('names_contacts')
    op.drop_table('emails_contacts')
    # ### end Alembic commands ###
