"""new and del tables

Revision ID: 37e220413bac
Revises: 
Create Date: 2022-09-05 01:08:16.365914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e220413bac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('names_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('second_name', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phones_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('names_to_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('names_contacts_id', sa.Integer(), nullable=True),
    sa.Column('emails_contacts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emails_contacts_id'], ['emails_contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['names_contacts_id'], ['names_contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('names_to_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('names_contacts_id', sa.Integer(), nullable=True),
    sa.Column('phones_contacts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['names_contacts_id'], ['names_contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phones_contacts_id'], ['phones_contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('names_to_phones')
    op.drop_table('names_to_emails')
    op.drop_table('phones_contacts')
    op.drop_table('names_contacts')
    op.drop_table('emails_contacts')
    # ### end Alembic commands ###
